services:
  mysql:
   image: mysql:8.3
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: eshop
   ports:
    - "3307:3306"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis