services:
  mysql:
   image: mysql:8.3
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: eshop
   ports:
    - "3307:3306"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    depends_on:
      - mysql
      - redis
      - elasticsearch