### POST request to create a new product
POST localhost:8081/api/products
Content-Type: application/json

{
  "name": "Černé kalhoty",
  "description": "Elegantní bavlněné kalhoty",
  "price": 1599.99,
  "available": true,
  "categoryId": 1,
  "brandId": 2,
  "tags": "black,summer,casual,t-shirt,tshirt"
}

###