### PUT request update a Product
PUT http://localhost:8081/api/products/1
Content-Type: application/json

{
  "name": "Černé kalhoty",
  "description": "Elegantní bavlněné kalhoty",
  "price": 1599.99,
  "available": true,
  "categoryId": 1,
  "brandId": 2,
  "tags": "black,summer,casual,trousers,sports wear"
}

###